---
title: "KPMG virtual internship experience"
description: |
  This is a simple blog about the  experience I had when I took part in the KPMG virtual internship on theforage website, a challenging yet eye-opening experience..
author:
  - name: Oyemade Emmanuel
    url: 
date: 2023-02-14
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Little or no experience is gained when students get introduced to the technological world. When I was learning processes in data, I had no practical experience and I gained only technical skills. Companies all over the world have started investing in helping students, interns(both undergraduate and graduate) gain technical experience.

## About KPMG 
KPMG is a global network of professional firms providing Audit, Tax and Advisory services.KPMG delivers services in 164 countries all around the world.
KPMG helps clients all around the world make decisions consciously and help make more informed decisions, help with risk analysis and also help grasp opportunities that are hard to see or come by.

## About KPMG virtual internship
With the help of [TheForage](https://www.theforage.com) , KPMG has been able to empower employees and interns(referred to as trainees from here on) all around the world with the skills that are highly demanded by big shot companies. This program helps prepare trainees as data consultants(junior).
Helping trainees make use of their skill for relevant tasks that prepare them for the future and the career ahead of them. The trainees are challenged to use software such as Microsoft excel, Power point and also Microsoft Word. The challenges are quite tricky but nothing trainees whom have gone through the learning process would not be able to tackle, this training helps trainees be able to use their own initiative to tackle challenges, then they are given the opportunity to reflect on their work and the mistakes made by going through an experts example (trainees are advised to make use of this as a template for correction).

## Internship process
The internship starts off from an introductory video from an executive of KPMG introducing trainees to the company and what they have to gain partaking in the virtual program, trainees are made to know that the tasks are daily activities carried out by regular employees of KPMG on daily basis. The tasks trainees would be carrying out are then introduced briefly.

### Task 1 : Data Quality Assessment
This is the first task to be done on this program, trainees are employed to check out the data and assess it for flaws (basic data quality assessment), trainees check data qualities such as data integrity, duplicates, data completeness, data relevance and so on. Trainees are not expected to correct this observations but instead draft an email telling the client about the findings from your data quality assessment.

### Task 2 : Data Insights
In this task, trainees are expected to make a Power point presentation on the process carried out by the company, this presentation should contain the process taken including data exploration , model development , and interpretation and reporting. Trainees are expected to explain to the client how they are going to go about the analysis fo the data.

### Task 3 : Data Insights and Presentation
In the final task of this program, trainees are expected to create a dashboard that can be presented to the client. This dashboard/ report should not exceed three(3) pages and should contain relevant KPIs, this report would contain the company logo which has been provided for the trainees.

## Conclusion
This program has been able to not only bridge the gap between students and real world experience but also help employees attain relevant skills to be able to keep their jobs in the fast paced technological world. **This program is completely free and you get to do it at our own pace.** You are not expected to know it all and that is why you are employed to make use of the internet as much as you can and re do the  tasks as much as you can till you are satisfied with your own answer(solution). At the end of this program, you would understand what being a data analyst/ consultant entails and you would be able to make decisions if this is a path you would want to pursue based on first hand experience. There are also other programs from top companies on [Theforage](www.theforage.com) that you can take.

Thank you for reading! I am Oyemade Emmanuel, a Certified Associate Data Analyst by Microsoft and DataCamp.
